### ISSUE TITLE
Use Cmdliner

### ISSUE THREAD

**Issue by pedagand** [usubalang/usuba#10]

**Comment by pedagand** [comment]
In particular, move https://github.com/usubalang/usuba/blob/cbd2f9338cf1d0f6d030add19dc425ff39505ac9/src/usuba_AST.mli#L74 `config` somewhere else (it is not AST related).

**Comment by mattiasdrp** [comment]
Config has been moved to its own file in #51 with the creation of [src/config.mli](https://github.com/usubalang/usuba/blob/main/src/config.mli) and [configure.ml](https://github.com/usubalang/usuba/blob/main/configure.ml#L172-L228) generating a src/config.ml file with the definition of the record

Cmdliner is clearly not a priority, closing this issue for now
