### ISSUE TITLE
Dune no longer supports `external-lib-deps`

### ISSUE THREAD

**Issue by odiferousmint** [usubalang/usuba#13]
Hello.

**Dune** does *not* support `external-lib-deps` anymore[1], so you should just let the user handle the dependencies themselves. Alternatively, if the dependencies are OCaml packages, then you can just check the return value of `opam info <package name>`. It returns `0` if the package is installed, and `5` if the package is not installed (just check for `ret != 0`.

Plus, what is the reason for `icc`? Is it mandatory? Cannot it work with `gcc` or `clang`? I have successfully compiled `usuba` without it, but I have yet to test it. I suppose you are generating code that is compatible with `icc`, but I wonder what it is that is not compatible with the other two major C compilers, or if there are any other reasons than that.

[1] It got removed at version 3.0.0: https://github.com/ocaml/dune/blob/main/CHANGES.md#300-11022022

**Comment by pedagand** [comment]
About `icc`: Usuba produces C files, which are then compiled with `icc`, `clang` *and* `GCC`, after which we pick the most efficient binary. On some of our benchmarks (not many, in fact), `icc` produces better code than the other two.

But, arguably, we could make the `icc` dependency optional, same for `clang` and `gcc`. @mattiasdrp Is that something we could specify?

**Comment by odiferousmint** [comment]
> But, arguably, we could make the `icc` dependency optional,

I think `icc` is not in most Linux (and probably BSD) repositories so you would have to sign up and download it yourself. I am not even sure if it is free now or without a trial version. That said, making it optional would be probably the best, IMO.

**Comment by mattiasdrp** [comment]
Hi @odiferousmint 
I saw the change in dune 3.0 about external-lib-deps. I'll change it to `opam install --deps-only .` or something like this and test how it behaves.
We can of course make icc (and other C compilers) optional since some users will just want to produce C code with usuba and not compile the resulting files

> I think icc is not in most Linux (and probably BSD) repositories so you would have to sign up and download it yourself.

I didn't install it from my repository and did not have to sign up to install it but it took me a few hours to find out how to install it from sources.

I'll work on it

**Comment by odiferousmint** [comment]
Thanks! :) As for the "since some users will just want to produce C code with usuba and not compile the resulting files", exactly. I only wanted to produce C code.
