### ISSUE TITLE
Setup a CI

### ISSUE THREAD

**Issue by pedagand** [usubalang/usuba#2]
We would need something that automatically test the functional correctness (using reference vectors, at least) of the reference ciphers in `samples/usuba`, for every commit pushed to the repos.

I would also like a  system to check for performance regressions, running locally on my machine and reporting slow-down throughout the commit history *relatively to a given machine*. This could be setup as a pre-commit hook on our machines, perhaps.

**Comment by mattiasdrp** [comment]
https://bheisler.github.io/post/benchmarking-in-the-cloud/

It looks like there's a lot of noise when executing benchmarks on a VM. Putting this here to find it easily in case we need it

**Comment by pedagand** [comment]
Fixed by #16
